In [1]:
#9장 Numbpy 
#Numbpy : C언어로 구현되 파이썬 라이브러리 ,고성능의 수치계산을 위해 제작
#python에는 mean()을 사용할 수 없어 array처리 후 사용
# mean() ->평균값
import numpy as np #numpy 기본적으로 array라는 단위로 데이터를 관리하며 이에 대해 연산을 수행
#x = np.array([1,3,5,7,9,11]) # x = np.array(1,3,5) -> X
#x = np.array([1,3,5,7,9,11]).reshape(3,2) # 3의 2열로 바꿔라~ 2차원 배열을 원하는 모양으로 바꿀 수 있다.
x = np.array([[1,3,5],[2,4,6]])
a = np.array([ [1,2,3],[2,3,4] ])
y = np.ones([3,4]) #ones는 값을 다 1로 바꾸는 것
print("1차원 배열 mean() ",x.mean())
print("1차원 배열 mean() ",x.shape) 
print(x)
print(y)
print(x[1])
print("2차원 배열 mean() ",x.mean())
print("2차원 배열 shape ",x.shape)
list1 = [[1,11],[2,12],[3,13]] #파이썬의 list
print(list1[1][1]) 
# print(list1[:,1]) X <= 이 코드는 에러 
# 파이썬에서는 모든 원소에 2번째 해당하는 값을 가져오지 못하지만 numpy를 사용하며 가능 
np_arr = np.array(list1) #numpy로 한번 변환함
print("모든 원소에 2번째 해당하는 값 추출",np_arr[:,1]) #이 형식은 numpy에서만 지원이 된다.!!!!중요!!!!
#print(np.array(list1[:,1])) X <= 이 코드는 에러  numpy변환 전에 list1를 먼저 출력해서 안됨
print(np.array(np_arr[:,0])) 
print(np.array(list1[:][0]))

1차원 배열 mean()  3.5
1차원 배열 mean()  (2, 3)
[[1 3 5]
 [2 4 6]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[2 4 6]
2차원 배열 mean()  3.5
2차원 배열 shape  (2, 3)
12
모든 원소에 2번째 해당하는 값 추출 [11 12 13]
[1 2 3]
[ 1 11]


In [2]:
#numpy 수학적이거나 통계적인 것을 활용
import math
import numpy as np
#math.sqrt(2)
#math.sqrt([2,3,4]) X <= 이 코드는 에러
np.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

In [3]:
import math
import numpy as np

a = np.arange(15).reshape(3,5) #3행 5열
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
import math
import numpy as np

a = np.arange(15).reshape(3,5) #3행 5열
print(a[1][1])

6


In [7]:
import numpy as np
z_v = np.zeros((5,3))
print(z_v)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np
z_v = np.zeros(15).reshape((5,3))
z_v += 5
print(z_v)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [12]:
import numpy as np
z_v = np.ones(15).reshape((5,3))
z_v += 5
print(z_v)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [14]:
#전치 행렬 : 행과 열을 교환
#원하는 방향으로 바꾸기 가능
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr.transpose())

[[1 3]
 [2 4]]


In [18]:
#인덱스 별로 합을 구해서 출력
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

[5 7 9]


In [20]:
import numpy as np
s = np.array([1,2,3])
t = s + 1
print(t)

[2 3 4]


In [23]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[1])
print(x[:,1])

[4 5 6]
[2 5 8]


In [26]:
#x와 y의 1열에 해당하는 값을 서로 덧셈하여 출력
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
z = x[:,1] + y[:,1]
print(z)

[ 5 11 17]
